import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import { useAccount, useProvider, useSigner } from 'wagmi'
import { Text } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import axios from "axios";
import { useEffect, useState } from "react";

import PlayersList from '@/features/Players/PlayersList'
import NewPlayerForm from './player/NewPlayerForm'
import Player from './player/[id]'
import Link from 'next/link';

export default function Home() {
  const [player, setPlayer] = useState(null);
  const { address, isConnected } = useAccount()

  async function getAPIData() {
    const response = await fetch(`${`http://localhost:3000/api/v1/find?address=${address}`}`);
    return response.json();
  }

  useEffect(() => {
    let mounted = true;
    getAPIData().then((item) => {
      if (mounted) {
        setPlayer(item);
      }
    });
    return () => (mounted = false);
  }, [address]);



  return (
    <>
      <Head>
        <title>Alyra DApp : Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected ? (
          <div className="App">
            <div>
              {player ? (
                <>
                  <h2>{player.name}</h2>
                  <p>{player.wallet_address}</p>
                  <Link href="/player/[id]" as={`/player/${player.id}`}>
                    Voir le player #{player.id}
                  </Link>
                </>
              ) :
                <NewPlayerForm />
              }
            </div>
          </div>
        ) : (
          <Alert status='warning' width="50%">
            <AlertIcon />
            Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  )
}
